---
services:
  ocis:
    environment:
      ANTIVIRUS_SCANNER_TYPE: "clamav"
      ANTIVIRUS_CLAMAV_SOCKET: "/var/run/clamav/clamd.sock"
      # enable the antivirus service
      OCIS_ADD_RUN_SERVICES: "antivirus"
      # configure the antivirus service
      POSTPROCESSING_STEPS: "virusscan"
      # PROXY_TLS is set to "false", the download url has no https
      STORAGE_USERS_DATA_GATEWAY_URL: http://ocis:9200/data
    volumes:
      - "clamav-socket:/var/run/clamav"

  clamav:
    image: clamav/clamav:${CLAMAV_DOCKER_TAG:-latest}
    networks:
      ocis-net:
    volumes:
      - "clamav-socket:/tmp"
      - "clamav-db:/var/lib/clamav"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

volumes:
  clamav-socket:
  clamav-db:
